"""HTTP view exposing a single calendar as an unauthenticated iCalendar feed.

The URL itself carries the per-flow secret token (as a path segment) that
is validated in constant time. No Home Assistant Authorization header is
required or accepted, which is what lets native mobile/desktop calendar
apps subscribe directly. Only GET is exposed and only calendar.get_events
is ever called - this view can never mutate state.
"""
from __future__ import annotations

import hashlib
import logging
import secrets
from datetime import date, datetime, timedelta
from typing import Any, cast

from aiohttp import web
from homeassistant.components.http.view import (  # type: ignore[attr-defined]
    HomeAssistantView,
)
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.dispatcher import async_dispatcher_send
from homeassistant.util import dt as dt_util
from icalendar import Calendar, Event

from .const import (
    ATTR_EVENT_COUNT,
    ATTR_LAST_ACCESSED,
    CONF_CALENDAR_ENTITY_ID,
    CONF_DAYS_AHEAD,
    CONF_DAYS_BEHIND,
    CONF_FULL_CALENDAR,
    CONF_TOKEN,
    DEFAULT_DAYS_AHEAD,
    DEFAULT_DAYS_BEHIND,
    DEFAULT_FULL_CALENDAR,
    DOMAIN,
    FULL_CALENDAR_YEARS,
    SIGNAL_FLOW_ACCESSED,
)

_LOGGER = logging.getLogger(__name__)


class CalendarShareView(HomeAssistantView):
    """Serve GET /api/calendar_share/{token} as text/calendar.

    The token alone identifies the flow: it is generated by us inside the
    config flow, so the share URL can be shown immediately on creation
    without waiting on a config-entry id that Home Assistant only assigns
    once the flow has finished (and which does not match the flow's own
    id). Every stored token is compared in constant time; only the config
    entry that matches is used.
    """

    url = "/api/calendar_share/{token}"
    name = "api:calendar_share"
    requires_auth = False

    def __init__(self, hass: HomeAssistant) -> None:
        self._hass = hass

    async def get(self, request: web.Request, token: str) -> web.Response:
        entry = self._find_entry_by_token(token)

        # Do not log the presented token, valid or not.
        if entry is None:
            _LOGGER.info("Calendar share request rejected: unknown token")
            return web.Response(status=403)

        entry_id = entry.entry_id
        entity_id: str = entry.data[CONF_CALENDAR_ENTITY_ID]

        if entry.options.get(CONF_FULL_CALENDAR, DEFAULT_FULL_CALENDAR):
            days_ahead = days_behind = 365 * FULL_CALENDAR_YEARS
        else:
            days_ahead = entry.options.get(CONF_DAYS_AHEAD, DEFAULT_DAYS_AHEAD)
            days_behind = entry.options.get(CONF_DAYS_BEHIND, DEFAULT_DAYS_BEHIND)

        events = await self._async_get_events(entity_id, days_ahead, days_behind)
        ics_body = self._build_ics(entity_id, events)

        async_dispatcher_send(
            self._hass,
            SIGNAL_FLOW_ACCESSED.format(entry_id=entry_id),
            {
                ATTR_LAST_ACCESSED: dt_util.utcnow(),
                ATTR_EVENT_COUNT: len(events),
            },
        )

        return web.Response(
            body=ics_body,
            content_type="text/calendar",
            charset="utf-8",
        )

    def _find_entry_by_token(self, presented_token: str) -> ConfigEntry | None:
        """Constant-time-compare the presented token against every flow."""
        domain_data = self._hass.data.get(DOMAIN, {})
        for key, flow in domain_data.items():
            if key == "view_registered":
                continue
            entry: ConfigEntry = flow["entry"]
            expected_token: str = entry.data[CONF_TOKEN]
            if secrets.compare_digest(presented_token, expected_token):
                return entry
        return None

    async def _async_get_events(
        self, entity_id: str, days_ahead: int, days_behind: int
    ) -> list[dict[str, Any]]:
        now = dt_util.now()
        start = now - timedelta(days=days_behind)
        end = now + timedelta(days=days_ahead)

        response = await self._hass.services.async_call(
            "calendar",
            "get_events",
            {
                "entity_id": entity_id,
                "start_date_time": start.isoformat(),
                "end_date_time": end.isoformat(),
            },
            blocking=True,
            return_response=True,
        )
        result_for_entity = (response or {}).get(entity_id)
        if not isinstance(result_for_entity, dict):
            return []
        events = result_for_entity.get("events", [])
        if not isinstance(events, list):
            return []
        return cast("list[dict[str, Any]]", events)

    @staticmethod
    def _build_ics(entity_id: str, events: list[dict[str, Any]]) -> bytes:
        calendar = Calendar()
        calendar.add("prodid", "-//Calendar Share//Home Assistant//EN")
        calendar.add("version", "2.0")
        calendar.add("calscale", "GREGORIAN")
        calendar.add("x-wr-timezone", "Europe/Paris")

        for event in events:
            calendar.add_component(_event_to_vevent(entity_id, event))

        return bytes(calendar.to_ical())


def _event_to_vevent(entity_id: str, event: dict[str, Any]) -> Event:
    """Convert a calendar.get_events event dict into an icalendar Event."""
    vevent = Event()

    raw_uid = event.get("uid") or f"{event.get('summary', '')}|{event['start']}"
    stable_uid = hashlib.sha256(f"{entity_id}:{raw_uid}".encode()).hexdigest()
    vevent.add("uid", f"{stable_uid}@calendar-share")

    vevent.add("summary", event.get("summary", ""))
    if event.get("description"):
        vevent.add("description", event["description"])
    if event.get("location"):
        vevent.add("location", event["location"])

    start = _parse_event_datetime(event["start"])
    end = _parse_event_datetime(event["end"])
    vevent.add("dtstart", start)
    vevent.add("dtend", end)
    vevent.add("dtstamp", dt_util.utcnow())

    return vevent


def _parse_event_datetime(value: str) -> date | datetime:
    """Return a date for all-day events, or a tz-aware datetime otherwise."""
    if len(value) == 10:
        return datetime.strptime(value, "%Y-%m-%d").date()
    return dt_util.parse_datetime(value) or dt_util.utcnow()
